fix(): minor fixes

diff --git a/viewer/platform/app/.recipes/Nginx-Orthanc/dockerfile b/viewer/platform/app/.recipes/Nginx-Orthanc/dockerfile
--- a/viewer/platform/app/.recipes/Nginx-Orthanc/dockerfile
+++ b/viewer/platform/app/.recipes/Nginx-Orthanc/dockerfile
@@ -2,26 +2,33 @@
 FROM node:18.16.1-slim as builder
 
 # Setup the working directory
-RUN mkdir /usr/src/app
 WORKDIR /usr/src/app
 
 # Install dependencies
 # apt-get update is combined with apt-get install to avoid using outdated packages
-RUN apt-get update && apt-get install -y build-essential python3
+RUN apt-get update && apt-get install -y build-essential python3 tree
 
-# Copy package.json and other dependency-related files first
-# Assuming your package.json and yarn.lock or similar are located in the project root
+# Copy package.json and yarn.lock first
+COPY package.json yarn.lock ./
 
-COPY ./ /usr/src/app/
+# Copy the rest of the application code
+COPY . .
+
+# Debug: List contents of the current directory
+RUN echo "Contents of /usr/src/app:" && ls -la
+
+# Debug: Display the content of package.json if it exists
+RUN cat package.json || echo "package.json not found"
 
 # Install node dependencies
 RUN yarn config set workspaces-experimental true
 RUN yarn install
 
-# Copy the rest of the application code
-
 # set QUICK_BUILD to true to make the build faster for dev
 ENV APP_CONFIG=config/docker-nginx-orthanc.js
+
+# Debug: List contents after yarn install
+RUN echo "Contents after yarn install:" && ls -la
 
 # Build the application
 RUN yarn run build
